/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnerLayoutRouteImport } from './routes/learner/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as websiteLayoutRouteImport } from './routes/(website)/_layout'
import { Route as websiteLayoutIndexRouteImport } from './routes/(website)/_layout/index'
import { Route as LearnerLayoutProfileRouteImport } from './routes/learner/_layout/profile'
import { Route as AdminLayoutProfileRouteImport } from './routes/admin/_layout/profile'
import { Route as AdminLayoutModuleNewModuleRouteImport } from './routes/admin/_layout/module/new-module'
import { Route as AdminLayoutModuleAllModulesRouteImport } from './routes/admin/_layout/module/all-modules'
import { Route as AdminLayoutCourseNewCourseRouteImport } from './routes/admin/_layout/course/new-course'
import { Route as AdminLayoutCourseAllCoursesRouteImport } from './routes/admin/_layout/course/all-courses'
import { Route as websiteLayoutauthSigninRouteImport } from './routes/(website)/_layout/(auth)/signin'
import { Route as websiteLayoutauthGithubCallbackRouteImport } from './routes/(website)/_layout/(auth)/github-callback'
import { Route as AdminLayoutModuleModuleIdEditModuleRouteImport } from './routes/admin/_layout/module/$moduleId.edit-module'
import { Route as AdminLayoutCourseCourseIdEditCourseRouteImport } from './routes/admin/_layout/course/$courseId.edit-course'

const LearnerRouteImport = createFileRoute('/learner')()
const AdminRouteImport = createFileRoute('/admin')()
const websiteRouteImport = createFileRoute('/(website)')()

const LearnerRoute = LearnerRouteImport.update({
  id: '/learner',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const websiteRoute = websiteRouteImport.update({
  id: '/(website)',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerLayoutRoute = LearnerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LearnerRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const websiteLayoutRoute = websiteLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => websiteRoute,
} as any)
const websiteLayoutIndexRoute = websiteLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => websiteLayoutRoute,
} as any)
const LearnerLayoutProfileRoute = LearnerLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LearnerLayoutRoute,
} as any)
const AdminLayoutProfileRoute = AdminLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutModuleNewModuleRoute =
  AdminLayoutModuleNewModuleRouteImport.update({
    id: '/module/new-module',
    path: '/module/new-module',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutModuleAllModulesRoute =
  AdminLayoutModuleAllModulesRouteImport.update({
    id: '/module/all-modules',
    path: '/module/all-modules',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCourseNewCourseRoute =
  AdminLayoutCourseNewCourseRouteImport.update({
    id: '/course/new-course',
    path: '/course/new-course',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCourseAllCoursesRoute =
  AdminLayoutCourseAllCoursesRouteImport.update({
    id: '/course/all-courses',
    path: '/course/all-courses',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const websiteLayoutauthSigninRoute = websiteLayoutauthSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => websiteLayoutRoute,
} as any)
const websiteLayoutauthGithubCallbackRoute =
  websiteLayoutauthGithubCallbackRouteImport.update({
    id: '/(auth)/github-callback',
    path: '/github-callback',
    getParentRoute: () => websiteLayoutRoute,
  } as any)
const AdminLayoutModuleModuleIdEditModuleRoute =
  AdminLayoutModuleModuleIdEditModuleRouteImport.update({
    id: '/module/$moduleId/edit-module',
    path: '/module/$moduleId/edit-module',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCourseCourseIdEditCourseRoute =
  AdminLayoutCourseCourseIdEditCourseRouteImport.update({
    id: '/course/$courseId/edit-course',
    path: '/course/$courseId/edit-course',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof websiteLayoutIndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/learner': typeof LearnerLayoutRouteWithChildren
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/learner/profile': typeof LearnerLayoutProfileRoute
  '/github-callback': typeof websiteLayoutauthGithubCallbackRoute
  '/signin': typeof websiteLayoutauthSigninRoute
  '/admin/course/all-courses': typeof AdminLayoutCourseAllCoursesRoute
  '/admin/course/new-course': typeof AdminLayoutCourseNewCourseRoute
  '/admin/module/all-modules': typeof AdminLayoutModuleAllModulesRoute
  '/admin/module/new-module': typeof AdminLayoutModuleNewModuleRoute
  '/admin/course/$courseId/edit-course': typeof AdminLayoutCourseCourseIdEditCourseRoute
  '/admin/module/$moduleId/edit-module': typeof AdminLayoutModuleModuleIdEditModuleRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminLayoutRouteWithChildren
  '/learner': typeof LearnerLayoutRouteWithChildren
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/learner/profile': typeof LearnerLayoutProfileRoute
  '/': typeof websiteLayoutIndexRoute
  '/github-callback': typeof websiteLayoutauthGithubCallbackRoute
  '/signin': typeof websiteLayoutauthSigninRoute
  '/admin/course/all-courses': typeof AdminLayoutCourseAllCoursesRoute
  '/admin/course/new-course': typeof AdminLayoutCourseNewCourseRoute
  '/admin/module/all-modules': typeof AdminLayoutModuleAllModulesRoute
  '/admin/module/new-module': typeof AdminLayoutModuleNewModuleRoute
  '/admin/course/$courseId/edit-course': typeof AdminLayoutCourseCourseIdEditCourseRoute
  '/admin/module/$moduleId/edit-module': typeof AdminLayoutModuleModuleIdEditModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(website)': typeof websiteRouteWithChildren
  '/(website)/_layout': typeof websiteLayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/learner': typeof LearnerRouteWithChildren
  '/learner/_layout': typeof LearnerLayoutRouteWithChildren
  '/admin/_layout/profile': typeof AdminLayoutProfileRoute
  '/learner/_layout/profile': typeof LearnerLayoutProfileRoute
  '/(website)/_layout/': typeof websiteLayoutIndexRoute
  '/(website)/_layout/(auth)/github-callback': typeof websiteLayoutauthGithubCallbackRoute
  '/(website)/_layout/(auth)/signin': typeof websiteLayoutauthSigninRoute
  '/admin/_layout/course/all-courses': typeof AdminLayoutCourseAllCoursesRoute
  '/admin/_layout/course/new-course': typeof AdminLayoutCourseNewCourseRoute
  '/admin/_layout/module/all-modules': typeof AdminLayoutModuleAllModulesRoute
  '/admin/_layout/module/new-module': typeof AdminLayoutModuleNewModuleRoute
  '/admin/_layout/course/$courseId/edit-course': typeof AdminLayoutCourseCourseIdEditCourseRoute
  '/admin/_layout/module/$moduleId/edit-module': typeof AdminLayoutModuleModuleIdEditModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/learner'
    | '/admin/profile'
    | '/learner/profile'
    | '/github-callback'
    | '/signin'
    | '/admin/course/all-courses'
    | '/admin/course/new-course'
    | '/admin/module/all-modules'
    | '/admin/module/new-module'
    | '/admin/course/$courseId/edit-course'
    | '/admin/module/$moduleId/edit-module'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/learner'
    | '/admin/profile'
    | '/learner/profile'
    | '/'
    | '/github-callback'
    | '/signin'
    | '/admin/course/all-courses'
    | '/admin/course/new-course'
    | '/admin/module/all-modules'
    | '/admin/module/new-module'
    | '/admin/course/$courseId/edit-course'
    | '/admin/module/$moduleId/edit-module'
  id:
    | '__root__'
    | '/(website)'
    | '/(website)/_layout'
    | '/admin'
    | '/admin/_layout'
    | '/learner'
    | '/learner/_layout'
    | '/admin/_layout/profile'
    | '/learner/_layout/profile'
    | '/(website)/_layout/'
    | '/(website)/_layout/(auth)/github-callback'
    | '/(website)/_layout/(auth)/signin'
    | '/admin/_layout/course/all-courses'
    | '/admin/_layout/course/new-course'
    | '/admin/_layout/module/all-modules'
    | '/admin/_layout/module/new-module'
    | '/admin/_layout/course/$courseId/edit-course'
    | '/admin/_layout/module/$moduleId/edit-module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  websiteRoute: typeof websiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LearnerRoute: typeof LearnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learner': {
      id: '/learner'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(website)': {
      id: '/(website)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/_layout': {
      id: '/learner/_layout'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerLayoutRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(website)/_layout': {
      id: '/(website)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteLayoutRouteImport
      parentRoute: typeof websiteRoute
    }
    '/(website)/_layout/': {
      id: '/(website)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteLayoutIndexRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/learner/_layout/profile': {
      id: '/learner/_layout/profile'
      path: '/profile'
      fullPath: '/learner/profile'
      preLoaderRoute: typeof LearnerLayoutProfileRouteImport
      parentRoute: typeof LearnerLayoutRoute
    }
    '/admin/_layout/profile': {
      id: '/admin/_layout/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminLayoutProfileRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/module/new-module': {
      id: '/admin/_layout/module/new-module'
      path: '/module/new-module'
      fullPath: '/admin/module/new-module'
      preLoaderRoute: typeof AdminLayoutModuleNewModuleRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/module/all-modules': {
      id: '/admin/_layout/module/all-modules'
      path: '/module/all-modules'
      fullPath: '/admin/module/all-modules'
      preLoaderRoute: typeof AdminLayoutModuleAllModulesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/course/new-course': {
      id: '/admin/_layout/course/new-course'
      path: '/course/new-course'
      fullPath: '/admin/course/new-course'
      preLoaderRoute: typeof AdminLayoutCourseNewCourseRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/course/all-courses': {
      id: '/admin/_layout/course/all-courses'
      path: '/course/all-courses'
      fullPath: '/admin/course/all-courses'
      preLoaderRoute: typeof AdminLayoutCourseAllCoursesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/(website)/_layout/(auth)/signin': {
      id: '/(website)/_layout/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof websiteLayoutauthSigninRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/(website)/_layout/(auth)/github-callback': {
      id: '/(website)/_layout/(auth)/github-callback'
      path: '/github-callback'
      fullPath: '/github-callback'
      preLoaderRoute: typeof websiteLayoutauthGithubCallbackRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/admin/_layout/module/$moduleId/edit-module': {
      id: '/admin/_layout/module/$moduleId/edit-module'
      path: '/module/$moduleId/edit-module'
      fullPath: '/admin/module/$moduleId/edit-module'
      preLoaderRoute: typeof AdminLayoutModuleModuleIdEditModuleRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/course/$courseId/edit-course': {
      id: '/admin/_layout/course/$courseId/edit-course'
      path: '/course/$courseId/edit-course'
      fullPath: '/admin/course/$courseId/edit-course'
      preLoaderRoute: typeof AdminLayoutCourseCourseIdEditCourseRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface websiteLayoutRouteChildren {
  websiteLayoutIndexRoute: typeof websiteLayoutIndexRoute
  websiteLayoutauthGithubCallbackRoute: typeof websiteLayoutauthGithubCallbackRoute
  websiteLayoutauthSigninRoute: typeof websiteLayoutauthSigninRoute
}

const websiteLayoutRouteChildren: websiteLayoutRouteChildren = {
  websiteLayoutIndexRoute: websiteLayoutIndexRoute,
  websiteLayoutauthGithubCallbackRoute: websiteLayoutauthGithubCallbackRoute,
  websiteLayoutauthSigninRoute: websiteLayoutauthSigninRoute,
}

const websiteLayoutRouteWithChildren = websiteLayoutRoute._addFileChildren(
  websiteLayoutRouteChildren,
)

interface websiteRouteChildren {
  websiteLayoutRoute: typeof websiteLayoutRouteWithChildren
}

const websiteRouteChildren: websiteRouteChildren = {
  websiteLayoutRoute: websiteLayoutRouteWithChildren,
}

const websiteRouteWithChildren =
  websiteRoute._addFileChildren(websiteRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutProfileRoute: typeof AdminLayoutProfileRoute
  AdminLayoutCourseAllCoursesRoute: typeof AdminLayoutCourseAllCoursesRoute
  AdminLayoutCourseNewCourseRoute: typeof AdminLayoutCourseNewCourseRoute
  AdminLayoutModuleAllModulesRoute: typeof AdminLayoutModuleAllModulesRoute
  AdminLayoutModuleNewModuleRoute: typeof AdminLayoutModuleNewModuleRoute
  AdminLayoutCourseCourseIdEditCourseRoute: typeof AdminLayoutCourseCourseIdEditCourseRoute
  AdminLayoutModuleModuleIdEditModuleRoute: typeof AdminLayoutModuleModuleIdEditModuleRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutProfileRoute: AdminLayoutProfileRoute,
  AdminLayoutCourseAllCoursesRoute: AdminLayoutCourseAllCoursesRoute,
  AdminLayoutCourseNewCourseRoute: AdminLayoutCourseNewCourseRoute,
  AdminLayoutModuleAllModulesRoute: AdminLayoutModuleAllModulesRoute,
  AdminLayoutModuleNewModuleRoute: AdminLayoutModuleNewModuleRoute,
  AdminLayoutCourseCourseIdEditCourseRoute:
    AdminLayoutCourseCourseIdEditCourseRoute,
  AdminLayoutModuleModuleIdEditModuleRoute:
    AdminLayoutModuleModuleIdEditModuleRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LearnerLayoutRouteChildren {
  LearnerLayoutProfileRoute: typeof LearnerLayoutProfileRoute
}

const LearnerLayoutRouteChildren: LearnerLayoutRouteChildren = {
  LearnerLayoutProfileRoute: LearnerLayoutProfileRoute,
}

const LearnerLayoutRouteWithChildren = LearnerLayoutRoute._addFileChildren(
  LearnerLayoutRouteChildren,
)

interface LearnerRouteChildren {
  LearnerLayoutRoute: typeof LearnerLayoutRouteWithChildren
}

const LearnerRouteChildren: LearnerRouteChildren = {
  LearnerLayoutRoute: LearnerLayoutRouteWithChildren,
}

const LearnerRouteWithChildren =
  LearnerRoute._addFileChildren(LearnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  websiteRoute: websiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LearnerRoute: LearnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
