/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnerLayoutRouteImport } from './routes/learner/_layout'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as websiteLayoutRouteImport } from './routes/(website)/_layout'
import { Route as websiteLayoutIndexRouteImport } from './routes/(website)/_layout/index'
import { Route as LearnerLayoutProfileRouteImport } from './routes/learner/_layout/profile'
import { Route as LearnerLayoutBillingRouteImport } from './routes/learner/_layout/billing'
import { Route as AdminLayoutProfileRouteImport } from './routes/admin/_layout/profile'
import { Route as AdminLayoutLearnersRouteImport } from './routes/admin/_layout/learners'
import { Route as websiteLayoutLeaderboardRouteImport } from './routes/(website)/_layout/leaderboard'
import { Route as LearnerLayoutCoursesIndexRouteImport } from './routes/learner/_layout/courses/index'
import { Route as websiteLayoutCoursesIndexRouteImport } from './routes/(website)/_layout/courses/index'
import { Route as AdminLayoutModuleNewModuleRouteImport } from './routes/admin/_layout/module/new-module'
import { Route as AdminLayoutModuleAllModulesRouteImport } from './routes/admin/_layout/module/all-modules'
import { Route as AdminLayoutDashboardStatisticsRouteImport } from './routes/admin/_layout/dashboard/statistics'
import { Route as AdminLayoutDashboardOverviewRouteImport } from './routes/admin/_layout/dashboard/overview'
import { Route as AdminLayoutCourseNewCourseRouteImport } from './routes/admin/_layout/course/new-course'
import { Route as AdminLayoutCourseAllCoursesRouteImport } from './routes/admin/_layout/course/all-courses'
import { Route as AdminLayoutChapterNewChapterRouteImport } from './routes/admin/_layout/chapter/new-chapter'
import { Route as AdminLayoutChapterAllChaptersRouteImport } from './routes/admin/_layout/chapter/all-chapters'
import { Route as websiteLayoutauthSigninRouteImport } from './routes/(website)/_layout/(auth)/signin'
import { Route as websiteLayoutauthGithubCallbackRouteImport } from './routes/(website)/_layout/(auth)/github-callback'
import { Route as websiteLayoutCoursesCourseIdIndexRouteImport } from './routes/(website)/_layout/courses/$courseId/index'
import { Route as LearnerLayoutCoursesCourseIdModulesRouteImport } from './routes/learner/_layout/courses/$courseId/modules'
import { Route as AdminLayoutModuleModuleIdEditModuleRouteImport } from './routes/admin/_layout/module/$moduleId.edit-module'
import { Route as AdminLayoutLessonDQuizRouteImport } from './routes/admin/_layout/lesson/_d.quiz'
import { Route as AdminLayoutLessonCLessonContentRouteImport } from './routes/admin/_layout/lesson/_c.lesson-content'
import { Route as AdminLayoutLessonBNewLessonRouteImport } from './routes/admin/_layout/lesson/_b.new-lesson'
import { Route as AdminLayoutLessonAAllLessonsRouteImport } from './routes/admin/_layout/lesson/_a.all-lessons'
import { Route as AdminLayoutLessonLessonIdEditLessonRouteImport } from './routes/admin/_layout/lesson/$lessonId.edit-lesson'
import { Route as AdminLayoutCourseCourseIdEditCourseRouteImport } from './routes/admin/_layout/course/$courseId.edit-course'
import { Route as AdminLayoutChapterChapterIdEditChapterRouteImport } from './routes/admin/_layout/chapter/$chapterId.edit-chapter'
import { Route as LearnerLayoutCoursesCourseIdModuleIdChaptersRouteImport } from './routes/learner/_layout/courses/$courseId/$moduleId/chapters'
import { Route as LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRouteImport } from './routes/learner/_layout/courses/$courseId/$moduleId/$chapterId/lesson'
import { Route as LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRouteImport } from './routes/learner/_layout/courses/$courseId/$moduleId/$chapterId/chapter-complete'

const LearnerRouteImport = createFileRoute('/learner')()
const AdminRouteImport = createFileRoute('/admin')()
const websiteRouteImport = createFileRoute('/(website)')()

const LearnerRoute = LearnerRouteImport.update({
  id: '/learner',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const websiteRoute = websiteRouteImport.update({
  id: '/(website)',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerLayoutRoute = LearnerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LearnerRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const websiteLayoutRoute = websiteLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => websiteRoute,
} as any)
const websiteLayoutIndexRoute = websiteLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => websiteLayoutRoute,
} as any)
const LearnerLayoutProfileRoute = LearnerLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LearnerLayoutRoute,
} as any)
const LearnerLayoutBillingRoute = LearnerLayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => LearnerLayoutRoute,
} as any)
const AdminLayoutProfileRoute = AdminLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutLearnersRoute = AdminLayoutLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const websiteLayoutLeaderboardRoute =
  websiteLayoutLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => websiteLayoutRoute,
  } as any)
const LearnerLayoutCoursesIndexRoute =
  LearnerLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => LearnerLayoutRoute,
  } as any)
const websiteLayoutCoursesIndexRoute =
  websiteLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => websiteLayoutRoute,
  } as any)
const AdminLayoutModuleNewModuleRoute =
  AdminLayoutModuleNewModuleRouteImport.update({
    id: '/module/new-module',
    path: '/module/new-module',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutModuleAllModulesRoute =
  AdminLayoutModuleAllModulesRouteImport.update({
    id: '/module/all-modules',
    path: '/module/all-modules',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutDashboardStatisticsRoute =
  AdminLayoutDashboardStatisticsRouteImport.update({
    id: '/dashboard/statistics',
    path: '/dashboard/statistics',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutDashboardOverviewRoute =
  AdminLayoutDashboardOverviewRouteImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCourseNewCourseRoute =
  AdminLayoutCourseNewCourseRouteImport.update({
    id: '/course/new-course',
    path: '/course/new-course',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCourseAllCoursesRoute =
  AdminLayoutCourseAllCoursesRouteImport.update({
    id: '/course/all-courses',
    path: '/course/all-courses',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutChapterNewChapterRoute =
  AdminLayoutChapterNewChapterRouteImport.update({
    id: '/chapter/new-chapter',
    path: '/chapter/new-chapter',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutChapterAllChaptersRoute =
  AdminLayoutChapterAllChaptersRouteImport.update({
    id: '/chapter/all-chapters',
    path: '/chapter/all-chapters',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const websiteLayoutauthSigninRoute = websiteLayoutauthSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => websiteLayoutRoute,
} as any)
const websiteLayoutauthGithubCallbackRoute =
  websiteLayoutauthGithubCallbackRouteImport.update({
    id: '/(auth)/github-callback',
    path: '/github-callback',
    getParentRoute: () => websiteLayoutRoute,
  } as any)
const websiteLayoutCoursesCourseIdIndexRoute =
  websiteLayoutCoursesCourseIdIndexRouteImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => websiteLayoutRoute,
  } as any)
const LearnerLayoutCoursesCourseIdModulesRoute =
  LearnerLayoutCoursesCourseIdModulesRouteImport.update({
    id: '/courses/$courseId/modules',
    path: '/courses/$courseId/modules',
    getParentRoute: () => LearnerLayoutRoute,
  } as any)
const AdminLayoutModuleModuleIdEditModuleRoute =
  AdminLayoutModuleModuleIdEditModuleRouteImport.update({
    id: '/module/$moduleId/edit-module',
    path: '/module/$moduleId/edit-module',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutLessonDQuizRoute = AdminLayoutLessonDQuizRouteImport.update({
  id: '/lesson/_d/quiz',
  path: '/lesson/quiz',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutLessonCLessonContentRoute =
  AdminLayoutLessonCLessonContentRouteImport.update({
    id: '/lesson/_c/lesson-content',
    path: '/lesson/lesson-content',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutLessonBNewLessonRoute =
  AdminLayoutLessonBNewLessonRouteImport.update({
    id: '/lesson/_b/new-lesson',
    path: '/lesson/new-lesson',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutLessonAAllLessonsRoute =
  AdminLayoutLessonAAllLessonsRouteImport.update({
    id: '/lesson/_a/all-lessons',
    path: '/lesson/all-lessons',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutLessonLessonIdEditLessonRoute =
  AdminLayoutLessonLessonIdEditLessonRouteImport.update({
    id: '/lesson/$lessonId/edit-lesson',
    path: '/lesson/$lessonId/edit-lesson',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCourseCourseIdEditCourseRoute =
  AdminLayoutCourseCourseIdEditCourseRouteImport.update({
    id: '/course/$courseId/edit-course',
    path: '/course/$courseId/edit-course',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutChapterChapterIdEditChapterRoute =
  AdminLayoutChapterChapterIdEditChapterRouteImport.update({
    id: '/chapter/$chapterId/edit-chapter',
    path: '/chapter/$chapterId/edit-chapter',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const LearnerLayoutCoursesCourseIdModuleIdChaptersRoute =
  LearnerLayoutCoursesCourseIdModuleIdChaptersRouteImport.update({
    id: '/courses/$courseId/$moduleId/chapters',
    path: '/courses/$courseId/$moduleId/chapters',
    getParentRoute: () => LearnerLayoutRoute,
  } as any)
const LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRoute =
  LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRouteImport.update({
    id: '/courses/$courseId/$moduleId/$chapterId/lesson',
    path: '/courses/$courseId/$moduleId/$chapterId/lesson',
    getParentRoute: () => LearnerLayoutRoute,
  } as any)
const LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRoute =
  LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRouteImport.update(
    {
      id: '/courses/$courseId/$moduleId/$chapterId/chapter-complete',
      path: '/courses/$courseId/$moduleId/$chapterId/chapter-complete',
      getParentRoute: () => LearnerLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof websiteLayoutIndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/learner': typeof LearnerLayoutRouteWithChildren
  '/leaderboard': typeof websiteLayoutLeaderboardRoute
  '/admin/learners': typeof AdminLayoutLearnersRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/learner/billing': typeof LearnerLayoutBillingRoute
  '/learner/profile': typeof LearnerLayoutProfileRoute
  '/github-callback': typeof websiteLayoutauthGithubCallbackRoute
  '/signin': typeof websiteLayoutauthSigninRoute
  '/admin/chapter/all-chapters': typeof AdminLayoutChapterAllChaptersRoute
  '/admin/chapter/new-chapter': typeof AdminLayoutChapterNewChapterRoute
  '/admin/course/all-courses': typeof AdminLayoutCourseAllCoursesRoute
  '/admin/course/new-course': typeof AdminLayoutCourseNewCourseRoute
  '/admin/dashboard/overview': typeof AdminLayoutDashboardOverviewRoute
  '/admin/dashboard/statistics': typeof AdminLayoutDashboardStatisticsRoute
  '/admin/module/all-modules': typeof AdminLayoutModuleAllModulesRoute
  '/admin/module/new-module': typeof AdminLayoutModuleNewModuleRoute
  '/courses': typeof websiteLayoutCoursesIndexRoute
  '/learner/courses': typeof LearnerLayoutCoursesIndexRoute
  '/admin/chapter/$chapterId/edit-chapter': typeof AdminLayoutChapterChapterIdEditChapterRoute
  '/admin/course/$courseId/edit-course': typeof AdminLayoutCourseCourseIdEditCourseRoute
  '/admin/lesson/$lessonId/edit-lesson': typeof AdminLayoutLessonLessonIdEditLessonRoute
  '/admin/lesson/all-lessons': typeof AdminLayoutLessonAAllLessonsRoute
  '/admin/lesson/new-lesson': typeof AdminLayoutLessonBNewLessonRoute
  '/admin/lesson/lesson-content': typeof AdminLayoutLessonCLessonContentRoute
  '/admin/lesson/quiz': typeof AdminLayoutLessonDQuizRoute
  '/admin/module/$moduleId/edit-module': typeof AdminLayoutModuleModuleIdEditModuleRoute
  '/learner/courses/$courseId/modules': typeof LearnerLayoutCoursesCourseIdModulesRoute
  '/courses/$courseId': typeof websiteLayoutCoursesCourseIdIndexRoute
  '/learner/courses/$courseId/$moduleId/chapters': typeof LearnerLayoutCoursesCourseIdModuleIdChaptersRoute
  '/learner/courses/$courseId/$moduleId/$chapterId/chapter-complete': typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRoute
  '/learner/courses/$courseId/$moduleId/$chapterId/lesson': typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminLayoutRouteWithChildren
  '/learner': typeof LearnerLayoutRouteWithChildren
  '/leaderboard': typeof websiteLayoutLeaderboardRoute
  '/admin/learners': typeof AdminLayoutLearnersRoute
  '/admin/profile': typeof AdminLayoutProfileRoute
  '/learner/billing': typeof LearnerLayoutBillingRoute
  '/learner/profile': typeof LearnerLayoutProfileRoute
  '/': typeof websiteLayoutIndexRoute
  '/github-callback': typeof websiteLayoutauthGithubCallbackRoute
  '/signin': typeof websiteLayoutauthSigninRoute
  '/admin/chapter/all-chapters': typeof AdminLayoutChapterAllChaptersRoute
  '/admin/chapter/new-chapter': typeof AdminLayoutChapterNewChapterRoute
  '/admin/course/all-courses': typeof AdminLayoutCourseAllCoursesRoute
  '/admin/course/new-course': typeof AdminLayoutCourseNewCourseRoute
  '/admin/dashboard/overview': typeof AdminLayoutDashboardOverviewRoute
  '/admin/dashboard/statistics': typeof AdminLayoutDashboardStatisticsRoute
  '/admin/module/all-modules': typeof AdminLayoutModuleAllModulesRoute
  '/admin/module/new-module': typeof AdminLayoutModuleNewModuleRoute
  '/courses': typeof websiteLayoutCoursesIndexRoute
  '/learner/courses': typeof LearnerLayoutCoursesIndexRoute
  '/admin/chapter/$chapterId/edit-chapter': typeof AdminLayoutChapterChapterIdEditChapterRoute
  '/admin/course/$courseId/edit-course': typeof AdminLayoutCourseCourseIdEditCourseRoute
  '/admin/lesson/$lessonId/edit-lesson': typeof AdminLayoutLessonLessonIdEditLessonRoute
  '/admin/lesson/all-lessons': typeof AdminLayoutLessonAAllLessonsRoute
  '/admin/lesson/new-lesson': typeof AdminLayoutLessonBNewLessonRoute
  '/admin/lesson/lesson-content': typeof AdminLayoutLessonCLessonContentRoute
  '/admin/lesson/quiz': typeof AdminLayoutLessonDQuizRoute
  '/admin/module/$moduleId/edit-module': typeof AdminLayoutModuleModuleIdEditModuleRoute
  '/learner/courses/$courseId/modules': typeof LearnerLayoutCoursesCourseIdModulesRoute
  '/courses/$courseId': typeof websiteLayoutCoursesCourseIdIndexRoute
  '/learner/courses/$courseId/$moduleId/chapters': typeof LearnerLayoutCoursesCourseIdModuleIdChaptersRoute
  '/learner/courses/$courseId/$moduleId/$chapterId/chapter-complete': typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRoute
  '/learner/courses/$courseId/$moduleId/$chapterId/lesson': typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(website)': typeof websiteRouteWithChildren
  '/(website)/_layout': typeof websiteLayoutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/learner': typeof LearnerRouteWithChildren
  '/learner/_layout': typeof LearnerLayoutRouteWithChildren
  '/(website)/_layout/leaderboard': typeof websiteLayoutLeaderboardRoute
  '/admin/_layout/learners': typeof AdminLayoutLearnersRoute
  '/admin/_layout/profile': typeof AdminLayoutProfileRoute
  '/learner/_layout/billing': typeof LearnerLayoutBillingRoute
  '/learner/_layout/profile': typeof LearnerLayoutProfileRoute
  '/(website)/_layout/': typeof websiteLayoutIndexRoute
  '/(website)/_layout/(auth)/github-callback': typeof websiteLayoutauthGithubCallbackRoute
  '/(website)/_layout/(auth)/signin': typeof websiteLayoutauthSigninRoute
  '/admin/_layout/chapter/all-chapters': typeof AdminLayoutChapterAllChaptersRoute
  '/admin/_layout/chapter/new-chapter': typeof AdminLayoutChapterNewChapterRoute
  '/admin/_layout/course/all-courses': typeof AdminLayoutCourseAllCoursesRoute
  '/admin/_layout/course/new-course': typeof AdminLayoutCourseNewCourseRoute
  '/admin/_layout/dashboard/overview': typeof AdminLayoutDashboardOverviewRoute
  '/admin/_layout/dashboard/statistics': typeof AdminLayoutDashboardStatisticsRoute
  '/admin/_layout/module/all-modules': typeof AdminLayoutModuleAllModulesRoute
  '/admin/_layout/module/new-module': typeof AdminLayoutModuleNewModuleRoute
  '/(website)/_layout/courses/': typeof websiteLayoutCoursesIndexRoute
  '/learner/_layout/courses/': typeof LearnerLayoutCoursesIndexRoute
  '/admin/_layout/chapter/$chapterId/edit-chapter': typeof AdminLayoutChapterChapterIdEditChapterRoute
  '/admin/_layout/course/$courseId/edit-course': typeof AdminLayoutCourseCourseIdEditCourseRoute
  '/admin/_layout/lesson/$lessonId/edit-lesson': typeof AdminLayoutLessonLessonIdEditLessonRoute
  '/admin/_layout/lesson/_a/all-lessons': typeof AdminLayoutLessonAAllLessonsRoute
  '/admin/_layout/lesson/_b/new-lesson': typeof AdminLayoutLessonBNewLessonRoute
  '/admin/_layout/lesson/_c/lesson-content': typeof AdminLayoutLessonCLessonContentRoute
  '/admin/_layout/lesson/_d/quiz': typeof AdminLayoutLessonDQuizRoute
  '/admin/_layout/module/$moduleId/edit-module': typeof AdminLayoutModuleModuleIdEditModuleRoute
  '/learner/_layout/courses/$courseId/modules': typeof LearnerLayoutCoursesCourseIdModulesRoute
  '/(website)/_layout/courses/$courseId/': typeof websiteLayoutCoursesCourseIdIndexRoute
  '/learner/_layout/courses/$courseId/$moduleId/chapters': typeof LearnerLayoutCoursesCourseIdModuleIdChaptersRoute
  '/learner/_layout/courses/$courseId/$moduleId/$chapterId/chapter-complete': typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRoute
  '/learner/_layout/courses/$courseId/$moduleId/$chapterId/lesson': typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/learner'
    | '/leaderboard'
    | '/admin/learners'
    | '/admin/profile'
    | '/learner/billing'
    | '/learner/profile'
    | '/github-callback'
    | '/signin'
    | '/admin/chapter/all-chapters'
    | '/admin/chapter/new-chapter'
    | '/admin/course/all-courses'
    | '/admin/course/new-course'
    | '/admin/dashboard/overview'
    | '/admin/dashboard/statistics'
    | '/admin/module/all-modules'
    | '/admin/module/new-module'
    | '/courses'
    | '/learner/courses'
    | '/admin/chapter/$chapterId/edit-chapter'
    | '/admin/course/$courseId/edit-course'
    | '/admin/lesson/$lessonId/edit-lesson'
    | '/admin/lesson/all-lessons'
    | '/admin/lesson/new-lesson'
    | '/admin/lesson/lesson-content'
    | '/admin/lesson/quiz'
    | '/admin/module/$moduleId/edit-module'
    | '/learner/courses/$courseId/modules'
    | '/courses/$courseId'
    | '/learner/courses/$courseId/$moduleId/chapters'
    | '/learner/courses/$courseId/$moduleId/$chapterId/chapter-complete'
    | '/learner/courses/$courseId/$moduleId/$chapterId/lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/learner'
    | '/leaderboard'
    | '/admin/learners'
    | '/admin/profile'
    | '/learner/billing'
    | '/learner/profile'
    | '/'
    | '/github-callback'
    | '/signin'
    | '/admin/chapter/all-chapters'
    | '/admin/chapter/new-chapter'
    | '/admin/course/all-courses'
    | '/admin/course/new-course'
    | '/admin/dashboard/overview'
    | '/admin/dashboard/statistics'
    | '/admin/module/all-modules'
    | '/admin/module/new-module'
    | '/courses'
    | '/learner/courses'
    | '/admin/chapter/$chapterId/edit-chapter'
    | '/admin/course/$courseId/edit-course'
    | '/admin/lesson/$lessonId/edit-lesson'
    | '/admin/lesson/all-lessons'
    | '/admin/lesson/new-lesson'
    | '/admin/lesson/lesson-content'
    | '/admin/lesson/quiz'
    | '/admin/module/$moduleId/edit-module'
    | '/learner/courses/$courseId/modules'
    | '/courses/$courseId'
    | '/learner/courses/$courseId/$moduleId/chapters'
    | '/learner/courses/$courseId/$moduleId/$chapterId/chapter-complete'
    | '/learner/courses/$courseId/$moduleId/$chapterId/lesson'
  id:
    | '__root__'
    | '/(website)'
    | '/(website)/_layout'
    | '/admin'
    | '/admin/_layout'
    | '/learner'
    | '/learner/_layout'
    | '/(website)/_layout/leaderboard'
    | '/admin/_layout/learners'
    | '/admin/_layout/profile'
    | '/learner/_layout/billing'
    | '/learner/_layout/profile'
    | '/(website)/_layout/'
    | '/(website)/_layout/(auth)/github-callback'
    | '/(website)/_layout/(auth)/signin'
    | '/admin/_layout/chapter/all-chapters'
    | '/admin/_layout/chapter/new-chapter'
    | '/admin/_layout/course/all-courses'
    | '/admin/_layout/course/new-course'
    | '/admin/_layout/dashboard/overview'
    | '/admin/_layout/dashboard/statistics'
    | '/admin/_layout/module/all-modules'
    | '/admin/_layout/module/new-module'
    | '/(website)/_layout/courses/'
    | '/learner/_layout/courses/'
    | '/admin/_layout/chapter/$chapterId/edit-chapter'
    | '/admin/_layout/course/$courseId/edit-course'
    | '/admin/_layout/lesson/$lessonId/edit-lesson'
    | '/admin/_layout/lesson/_a/all-lessons'
    | '/admin/_layout/lesson/_b/new-lesson'
    | '/admin/_layout/lesson/_c/lesson-content'
    | '/admin/_layout/lesson/_d/quiz'
    | '/admin/_layout/module/$moduleId/edit-module'
    | '/learner/_layout/courses/$courseId/modules'
    | '/(website)/_layout/courses/$courseId/'
    | '/learner/_layout/courses/$courseId/$moduleId/chapters'
    | '/learner/_layout/courses/$courseId/$moduleId/$chapterId/chapter-complete'
    | '/learner/_layout/courses/$courseId/$moduleId/$chapterId/lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  websiteRoute: typeof websiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LearnerRoute: typeof LearnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learner': {
      id: '/learner'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(website)': {
      id: '/(website)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/_layout': {
      id: '/learner/_layout'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerLayoutRouteImport
      parentRoute: typeof LearnerRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(website)/_layout': {
      id: '/(website)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteLayoutRouteImport
      parentRoute: typeof websiteRoute
    }
    '/(website)/_layout/': {
      id: '/(website)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof websiteLayoutIndexRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/learner/_layout/profile': {
      id: '/learner/_layout/profile'
      path: '/profile'
      fullPath: '/learner/profile'
      preLoaderRoute: typeof LearnerLayoutProfileRouteImport
      parentRoute: typeof LearnerLayoutRoute
    }
    '/learner/_layout/billing': {
      id: '/learner/_layout/billing'
      path: '/billing'
      fullPath: '/learner/billing'
      preLoaderRoute: typeof LearnerLayoutBillingRouteImport
      parentRoute: typeof LearnerLayoutRoute
    }
    '/admin/_layout/profile': {
      id: '/admin/_layout/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminLayoutProfileRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/learners': {
      id: '/admin/_layout/learners'
      path: '/learners'
      fullPath: '/admin/learners'
      preLoaderRoute: typeof AdminLayoutLearnersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/(website)/_layout/leaderboard': {
      id: '/(website)/_layout/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof websiteLayoutLeaderboardRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/learner/_layout/courses/': {
      id: '/learner/_layout/courses/'
      path: '/courses'
      fullPath: '/learner/courses'
      preLoaderRoute: typeof LearnerLayoutCoursesIndexRouteImport
      parentRoute: typeof LearnerLayoutRoute
    }
    '/(website)/_layout/courses/': {
      id: '/(website)/_layout/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof websiteLayoutCoursesIndexRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/admin/_layout/module/new-module': {
      id: '/admin/_layout/module/new-module'
      path: '/module/new-module'
      fullPath: '/admin/module/new-module'
      preLoaderRoute: typeof AdminLayoutModuleNewModuleRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/module/all-modules': {
      id: '/admin/_layout/module/all-modules'
      path: '/module/all-modules'
      fullPath: '/admin/module/all-modules'
      preLoaderRoute: typeof AdminLayoutModuleAllModulesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard/statistics': {
      id: '/admin/_layout/dashboard/statistics'
      path: '/dashboard/statistics'
      fullPath: '/admin/dashboard/statistics'
      preLoaderRoute: typeof AdminLayoutDashboardStatisticsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard/overview': {
      id: '/admin/_layout/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/admin/dashboard/overview'
      preLoaderRoute: typeof AdminLayoutDashboardOverviewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/course/new-course': {
      id: '/admin/_layout/course/new-course'
      path: '/course/new-course'
      fullPath: '/admin/course/new-course'
      preLoaderRoute: typeof AdminLayoutCourseNewCourseRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/course/all-courses': {
      id: '/admin/_layout/course/all-courses'
      path: '/course/all-courses'
      fullPath: '/admin/course/all-courses'
      preLoaderRoute: typeof AdminLayoutCourseAllCoursesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/chapter/new-chapter': {
      id: '/admin/_layout/chapter/new-chapter'
      path: '/chapter/new-chapter'
      fullPath: '/admin/chapter/new-chapter'
      preLoaderRoute: typeof AdminLayoutChapterNewChapterRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/chapter/all-chapters': {
      id: '/admin/_layout/chapter/all-chapters'
      path: '/chapter/all-chapters'
      fullPath: '/admin/chapter/all-chapters'
      preLoaderRoute: typeof AdminLayoutChapterAllChaptersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/(website)/_layout/(auth)/signin': {
      id: '/(website)/_layout/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof websiteLayoutauthSigninRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/(website)/_layout/(auth)/github-callback': {
      id: '/(website)/_layout/(auth)/github-callback'
      path: '/github-callback'
      fullPath: '/github-callback'
      preLoaderRoute: typeof websiteLayoutauthGithubCallbackRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/(website)/_layout/courses/$courseId/': {
      id: '/(website)/_layout/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof websiteLayoutCoursesCourseIdIndexRouteImport
      parentRoute: typeof websiteLayoutRoute
    }
    '/learner/_layout/courses/$courseId/modules': {
      id: '/learner/_layout/courses/$courseId/modules'
      path: '/courses/$courseId/modules'
      fullPath: '/learner/courses/$courseId/modules'
      preLoaderRoute: typeof LearnerLayoutCoursesCourseIdModulesRouteImport
      parentRoute: typeof LearnerLayoutRoute
    }
    '/admin/_layout/module/$moduleId/edit-module': {
      id: '/admin/_layout/module/$moduleId/edit-module'
      path: '/module/$moduleId/edit-module'
      fullPath: '/admin/module/$moduleId/edit-module'
      preLoaderRoute: typeof AdminLayoutModuleModuleIdEditModuleRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/lesson/_d/quiz': {
      id: '/admin/_layout/lesson/_d/quiz'
      path: '/lesson/quiz'
      fullPath: '/admin/lesson/quiz'
      preLoaderRoute: typeof AdminLayoutLessonDQuizRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/lesson/_c/lesson-content': {
      id: '/admin/_layout/lesson/_c/lesson-content'
      path: '/lesson/lesson-content'
      fullPath: '/admin/lesson/lesson-content'
      preLoaderRoute: typeof AdminLayoutLessonCLessonContentRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/lesson/_b/new-lesson': {
      id: '/admin/_layout/lesson/_b/new-lesson'
      path: '/lesson/new-lesson'
      fullPath: '/admin/lesson/new-lesson'
      preLoaderRoute: typeof AdminLayoutLessonBNewLessonRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/lesson/_a/all-lessons': {
      id: '/admin/_layout/lesson/_a/all-lessons'
      path: '/lesson/all-lessons'
      fullPath: '/admin/lesson/all-lessons'
      preLoaderRoute: typeof AdminLayoutLessonAAllLessonsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/lesson/$lessonId/edit-lesson': {
      id: '/admin/_layout/lesson/$lessonId/edit-lesson'
      path: '/lesson/$lessonId/edit-lesson'
      fullPath: '/admin/lesson/$lessonId/edit-lesson'
      preLoaderRoute: typeof AdminLayoutLessonLessonIdEditLessonRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/course/$courseId/edit-course': {
      id: '/admin/_layout/course/$courseId/edit-course'
      path: '/course/$courseId/edit-course'
      fullPath: '/admin/course/$courseId/edit-course'
      preLoaderRoute: typeof AdminLayoutCourseCourseIdEditCourseRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/chapter/$chapterId/edit-chapter': {
      id: '/admin/_layout/chapter/$chapterId/edit-chapter'
      path: '/chapter/$chapterId/edit-chapter'
      fullPath: '/admin/chapter/$chapterId/edit-chapter'
      preLoaderRoute: typeof AdminLayoutChapterChapterIdEditChapterRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/learner/_layout/courses/$courseId/$moduleId/chapters': {
      id: '/learner/_layout/courses/$courseId/$moduleId/chapters'
      path: '/courses/$courseId/$moduleId/chapters'
      fullPath: '/learner/courses/$courseId/$moduleId/chapters'
      preLoaderRoute: typeof LearnerLayoutCoursesCourseIdModuleIdChaptersRouteImport
      parentRoute: typeof LearnerLayoutRoute
    }
    '/learner/_layout/courses/$courseId/$moduleId/$chapterId/lesson': {
      id: '/learner/_layout/courses/$courseId/$moduleId/$chapterId/lesson'
      path: '/courses/$courseId/$moduleId/$chapterId/lesson'
      fullPath: '/learner/courses/$courseId/$moduleId/$chapterId/lesson'
      preLoaderRoute: typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRouteImport
      parentRoute: typeof LearnerLayoutRoute
    }
    '/learner/_layout/courses/$courseId/$moduleId/$chapterId/chapter-complete': {
      id: '/learner/_layout/courses/$courseId/$moduleId/$chapterId/chapter-complete'
      path: '/courses/$courseId/$moduleId/$chapterId/chapter-complete'
      fullPath: '/learner/courses/$courseId/$moduleId/$chapterId/chapter-complete'
      preLoaderRoute: typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRouteImport
      parentRoute: typeof LearnerLayoutRoute
    }
  }
}

interface websiteLayoutRouteChildren {
  websiteLayoutLeaderboardRoute: typeof websiteLayoutLeaderboardRoute
  websiteLayoutIndexRoute: typeof websiteLayoutIndexRoute
  websiteLayoutauthGithubCallbackRoute: typeof websiteLayoutauthGithubCallbackRoute
  websiteLayoutauthSigninRoute: typeof websiteLayoutauthSigninRoute
  websiteLayoutCoursesIndexRoute: typeof websiteLayoutCoursesIndexRoute
  websiteLayoutCoursesCourseIdIndexRoute: typeof websiteLayoutCoursesCourseIdIndexRoute
}

const websiteLayoutRouteChildren: websiteLayoutRouteChildren = {
  websiteLayoutLeaderboardRoute: websiteLayoutLeaderboardRoute,
  websiteLayoutIndexRoute: websiteLayoutIndexRoute,
  websiteLayoutauthGithubCallbackRoute: websiteLayoutauthGithubCallbackRoute,
  websiteLayoutauthSigninRoute: websiteLayoutauthSigninRoute,
  websiteLayoutCoursesIndexRoute: websiteLayoutCoursesIndexRoute,
  websiteLayoutCoursesCourseIdIndexRoute:
    websiteLayoutCoursesCourseIdIndexRoute,
}

const websiteLayoutRouteWithChildren = websiteLayoutRoute._addFileChildren(
  websiteLayoutRouteChildren,
)

interface websiteRouteChildren {
  websiteLayoutRoute: typeof websiteLayoutRouteWithChildren
}

const websiteRouteChildren: websiteRouteChildren = {
  websiteLayoutRoute: websiteLayoutRouteWithChildren,
}

const websiteRouteWithChildren =
  websiteRoute._addFileChildren(websiteRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutLearnersRoute: typeof AdminLayoutLearnersRoute
  AdminLayoutProfileRoute: typeof AdminLayoutProfileRoute
  AdminLayoutChapterAllChaptersRoute: typeof AdminLayoutChapterAllChaptersRoute
  AdminLayoutChapterNewChapterRoute: typeof AdminLayoutChapterNewChapterRoute
  AdminLayoutCourseAllCoursesRoute: typeof AdminLayoutCourseAllCoursesRoute
  AdminLayoutCourseNewCourseRoute: typeof AdminLayoutCourseNewCourseRoute
  AdminLayoutDashboardOverviewRoute: typeof AdminLayoutDashboardOverviewRoute
  AdminLayoutDashboardStatisticsRoute: typeof AdminLayoutDashboardStatisticsRoute
  AdminLayoutModuleAllModulesRoute: typeof AdminLayoutModuleAllModulesRoute
  AdminLayoutModuleNewModuleRoute: typeof AdminLayoutModuleNewModuleRoute
  AdminLayoutChapterChapterIdEditChapterRoute: typeof AdminLayoutChapterChapterIdEditChapterRoute
  AdminLayoutCourseCourseIdEditCourseRoute: typeof AdminLayoutCourseCourseIdEditCourseRoute
  AdminLayoutLessonLessonIdEditLessonRoute: typeof AdminLayoutLessonLessonIdEditLessonRoute
  AdminLayoutLessonAAllLessonsRoute: typeof AdminLayoutLessonAAllLessonsRoute
  AdminLayoutLessonBNewLessonRoute: typeof AdminLayoutLessonBNewLessonRoute
  AdminLayoutLessonCLessonContentRoute: typeof AdminLayoutLessonCLessonContentRoute
  AdminLayoutLessonDQuizRoute: typeof AdminLayoutLessonDQuizRoute
  AdminLayoutModuleModuleIdEditModuleRoute: typeof AdminLayoutModuleModuleIdEditModuleRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutLearnersRoute: AdminLayoutLearnersRoute,
  AdminLayoutProfileRoute: AdminLayoutProfileRoute,
  AdminLayoutChapterAllChaptersRoute: AdminLayoutChapterAllChaptersRoute,
  AdminLayoutChapterNewChapterRoute: AdminLayoutChapterNewChapterRoute,
  AdminLayoutCourseAllCoursesRoute: AdminLayoutCourseAllCoursesRoute,
  AdminLayoutCourseNewCourseRoute: AdminLayoutCourseNewCourseRoute,
  AdminLayoutDashboardOverviewRoute: AdminLayoutDashboardOverviewRoute,
  AdminLayoutDashboardStatisticsRoute: AdminLayoutDashboardStatisticsRoute,
  AdminLayoutModuleAllModulesRoute: AdminLayoutModuleAllModulesRoute,
  AdminLayoutModuleNewModuleRoute: AdminLayoutModuleNewModuleRoute,
  AdminLayoutChapterChapterIdEditChapterRoute:
    AdminLayoutChapterChapterIdEditChapterRoute,
  AdminLayoutCourseCourseIdEditCourseRoute:
    AdminLayoutCourseCourseIdEditCourseRoute,
  AdminLayoutLessonLessonIdEditLessonRoute:
    AdminLayoutLessonLessonIdEditLessonRoute,
  AdminLayoutLessonAAllLessonsRoute: AdminLayoutLessonAAllLessonsRoute,
  AdminLayoutLessonBNewLessonRoute: AdminLayoutLessonBNewLessonRoute,
  AdminLayoutLessonCLessonContentRoute: AdminLayoutLessonCLessonContentRoute,
  AdminLayoutLessonDQuizRoute: AdminLayoutLessonDQuizRoute,
  AdminLayoutModuleModuleIdEditModuleRoute:
    AdminLayoutModuleModuleIdEditModuleRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LearnerLayoutRouteChildren {
  LearnerLayoutBillingRoute: typeof LearnerLayoutBillingRoute
  LearnerLayoutProfileRoute: typeof LearnerLayoutProfileRoute
  LearnerLayoutCoursesIndexRoute: typeof LearnerLayoutCoursesIndexRoute
  LearnerLayoutCoursesCourseIdModulesRoute: typeof LearnerLayoutCoursesCourseIdModulesRoute
  LearnerLayoutCoursesCourseIdModuleIdChaptersRoute: typeof LearnerLayoutCoursesCourseIdModuleIdChaptersRoute
  LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRoute: typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRoute
  LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRoute: typeof LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRoute
}

const LearnerLayoutRouteChildren: LearnerLayoutRouteChildren = {
  LearnerLayoutBillingRoute: LearnerLayoutBillingRoute,
  LearnerLayoutProfileRoute: LearnerLayoutProfileRoute,
  LearnerLayoutCoursesIndexRoute: LearnerLayoutCoursesIndexRoute,
  LearnerLayoutCoursesCourseIdModulesRoute:
    LearnerLayoutCoursesCourseIdModulesRoute,
  LearnerLayoutCoursesCourseIdModuleIdChaptersRoute:
    LearnerLayoutCoursesCourseIdModuleIdChaptersRoute,
  LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRoute:
    LearnerLayoutCoursesCourseIdModuleIdChapterIdChapterCompleteRoute,
  LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRoute:
    LearnerLayoutCoursesCourseIdModuleIdChapterIdLessonRoute,
}

const LearnerLayoutRouteWithChildren = LearnerLayoutRoute._addFileChildren(
  LearnerLayoutRouteChildren,
)

interface LearnerRouteChildren {
  LearnerLayoutRoute: typeof LearnerLayoutRouteWithChildren
}

const LearnerRouteChildren: LearnerRouteChildren = {
  LearnerLayoutRoute: LearnerLayoutRouteWithChildren,
}

const LearnerRouteWithChildren =
  LearnerRoute._addFileChildren(LearnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  websiteRoute: websiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LearnerRoute: LearnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
